/**
 * Singleton Prisma client — Prisma 7.
 *
 * In Prisma 7 the client is generated into a custom output path (see the
 * `output` field in `prisma/schema.prisma`) and requires a driver adapter
 * to talk to the database. We use `@prisma/adapter-pg` against the
 * Supabase Postgres pooled connection (`DATABASE_URL`).
 *
 * In development we cache the client on `globalThis` so that hot-reloads
 * via `tsx watch` don't spawn a new pool on every reload.
 */
import { PrismaPg } from "@prisma/adapter-pg";
// eslint-disable-next-line import/no-unresolved -- generated by `prisma generate`
import { PrismaClient } from "../generated/prisma/client.js";
import logger from "./logger.js";

interface PrismaLogEvent {
  message: string;
  target: string;
  timestamp?: Date;
}

declare global {
  // eslint-disable-next-line no-var
  var __prisma: PrismaClient | undefined;
}

function getDatabaseUrl(): string {
  const url = process.env.DATABASE_URL;
  if (!url) {
    logger.error("DATABASE_URL is not set");
    throw new Error("DATABASE_URL is not configured");
  }
  return url;
}

function makeClient(): PrismaClient {
  const adapter = new PrismaPg({ connectionString: getDatabaseUrl() });
  const client = new PrismaClient({
    adapter,
    log: [
      { emit: "event", level: "error" },
      { emit: "event", level: "warn" },
    ],
  });

  // Forward Prisma's internal logs to Winston.
  client.$on("error", (event: PrismaLogEvent) => {
    logger.error("Prisma error", {
      message: event.message,
      target: event.target,
    });
  });
  client.$on("warn", (event: PrismaLogEvent) => {
    logger.warn("Prisma warning", {
      message: event.message,
      target: event.target,
    });
  });

  return client;
}

const prisma: PrismaClient = global.__prisma ?? makeClient();

if (process.env.NODE_ENV !== "production") {
  global.__prisma = prisma;
}

export default prisma;
